import Link from "next/link";
import { Roboto } from "next/font/google";
import { useRouter } from "next/router";
import Head from "next/head";

const font = Roboto({ subsets: ["latin"], weight: "400" });

export default function Layout({ children }) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>dentixt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/teeth.png" />
      </Head>
      <nav className="w-full p-6 flex flex-row space-between">
        <div className="basis-1/2">
          <Link href="/" className="text-xl">
            dentixt
          </Link>
        </div>
        <div className="basis-1/2 flex flex-row justify-end">
          {" "}
          <button
            className="border p-2 rounded-full border-gray-300 dark:focus:border-gray-500 focus:outline-none hover:border-gray-500"
            onClick={() => router.push("../registerClinic/form")}
          >
            Register your clinic
          </button>
        </div>
      </nav>
      <main>{children}</main>
    </>
  );
}
