import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [zipCode, setZipCode] = useState();
  return (
    <>
      <Head>
        <title>dentixt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my-10 ">
        <div className="flex justify-center flex-col items-center">
          <Link href="/" className="text-7xl mx-auto max-w-sm text-center">
            dentixt
          </Link>
          <Image
            src="/mouth.png"
            height="350"
            width="350"
            alt="An image of teeth"
            className="m-10"
          />
          <div className="m-10">
            <label>Enter your post code: </label>
            <input
              value={zipCode}
              onChange={(e) => setZipCode(e.target.value)}
              placeholder="43650"
              className="m-10 appearance-none border-2 p-3"
              type="number"
            />
          </div>
          <Link href={`/clinics/${zipCode}`}>
            <button
              className="rounded-full  border px-5 py-5"
              disabled={!zipCode}
            >
              Book your reservation now!
            </button>
          </Link>
        </div>
      </main>
    </>
  );
}
